/*
 * Astute Energy API Specification.
 * Rest enpoints to be used with the Angular application for Astute Energy.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.astute.electrical.dtos;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

@Data
public class DtrDevice implements Serializable {

	@JsonProperty("dtrDeviceId")
	private Integer dtrDeviceId;

	@JsonProperty("number")
	private Long number;

	@JsonProperty("vendorId")
	private Integer vendorId;

	@JsonProperty("dtrDtrDeviceMapping")
	private List<DtrDtrDeviceMapping> dtrDtrDeviceMapping;

	@JsonProperty("installationDate")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	private Date installationDate;

	@JsonProperty("simNumber")
	private Long simNumber;

	@JsonProperty("mobileNumber")
	private Long mobileNumber;

	@JsonProperty("telecomOperator")
	private String telecomOperator;

}
