/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorResponse;
import io.swagger.model.Line33kv;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-05-30T10:52:13.430Z[GMT]")
@Api(value = "Line33kv", description = "the Line33kv API")
public interface Line33kvApi {

    @ApiOperation(value = "Creates a Line33kv", nickname = "addLine33kv", notes = "add details about a Line33kv", response = Line33kv.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "electrical", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = Line33kv.class),
        @ApiResponse(code = 401, message = "Access token is missing or invalid.", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "The specified resource was not found.", response = ErrorResponse.class) })
    @RequestMapping(value = "/Line33kv",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Line33kv> addLine33kv(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Line33kv body);


    @ApiOperation(value = "returns a boolean value", nickname = "disableLine33kv", notes = "Here it will set the isActive field false", response = Boolean.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "electrical", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Accepted", response = Boolean.class),
        @ApiResponse(code = 401, message = "Access token is missing or invalid.", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "The specified resource was not found.", response = ErrorResponse.class) })
    @RequestMapping(value = "/Line33kv",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Boolean> disableLine33kv(@Min(0)@ApiParam(value = "id of the Line33kv to set isActive false.",required=true, allowableValues = "") @PathVariable("id") Integer id);


    @ApiOperation(value = "returns all Line33kv", nickname = "getAllLine33kv", notes = "get details about all Line33kv", response = Line33kv.class, responseContainer = "List", authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "electrical", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ok", response = Line33kv.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Access token is missing or invalid.", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "The specified resource was not found.", response = ErrorResponse.class) })
    @RequestMapping(value = "/Line33kv",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Line33kv>> getAllLine33kv();


    @ApiOperation(value = "returns a updated Line33kv", nickname = "updateLine33kv", notes = "update details about a Line33kv", response = Line33kv.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "electrical", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Accepted", response = Line33kv.class),
        @ApiResponse(code = 401, message = "Access token is missing or invalid.", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "The specified resource was not found.", response = ErrorResponse.class) })
    @RequestMapping(value = "/Line33kv",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Line33kv> updateLine33kv(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Line33kv body);

}
