/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CountResponse;
import io.swagger.model.Division;
import io.swagger.model.ErrorResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-06-01T10:15:14.735Z[GMT]")
@Api(value = "division", description = "the division API")
public interface DivisionApi {

    @ApiOperation(value = "returns a division", nickname = "addDivision", notes = "add details about a division", response = Division.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "discom", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = Division.class),
        @ApiResponse(code = 401, message = "Access token is missing or invalid.", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "The specified resource was not found.", response = ErrorResponse.class) })
    @RequestMapping(value = "/division",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Division> addDivision(@NotNull @Min(0)@ApiParam(value = "idCircle of the circle to fetch.", required = true, allowableValues = "") @Valid @RequestParam(value = "idCircle", required = true) Integer idCircle,@ApiParam(value = ""  )  @Valid @RequestBody Division body);


    @ApiOperation(value = "returns a division", nickname = "deleteDivision", notes = "delete details about a division", response = Division.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "discom", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Accepted", response = Division.class),
        @ApiResponse(code = 401, message = "Access token is missing or invalid.", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "The specified resource was not found.", response = ErrorResponse.class) })
    @RequestMapping(value = "/division/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Division> deleteDivision(@Min(0)@ApiParam(value = "id of the division to fetch.",required=true, allowableValues = "") @PathVariable("id") Integer id);


    @ApiOperation(value = "returns a division", nickname = "getAllDivision", notes = "get details about all division", response = Division.class, responseContainer = "List", authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "discom", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ok", response = Division.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Access token is missing or invalid.", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "The specified resource was not found.", response = ErrorResponse.class) })
    @RequestMapping(value = "/division",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Division>> getAllDivision(@NotNull @Min(0)@ApiParam(value = "idCircle of the circle to fetch.", required = true, allowableValues = "") @Valid @RequestParam(value = "idCircle", required = true) Integer idCircle,@ApiParam(value = "if provided, returns the divisions that match this name.") @Valid @RequestParam(value = "name", required = false) String name,@ApiParam(value = "if true, populates all nested entities.") @Valid @RequestParam(value = "populate", required = false) Boolean populate);


    @ApiOperation(value = "returns a division", nickname = "getDivision", notes = "get details about a division", response = Division.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "discom", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ok", response = Division.class),
        @ApiResponse(code = 401, message = "Access token is missing or invalid.", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "The specified resource was not found.", response = ErrorResponse.class) })
    @RequestMapping(value = "/division/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Division> getDivision(@Min(0)@ApiParam(value = "id of the division to fetch.",required=true, allowableValues = "") @PathVariable("id") Integer id,@ApiParam(value = "if true, populates all nested entities.") @Valid @RequestParam(value = "populate", required = false) Boolean populate);


    @ApiOperation(value = "returns number of divisions in a circle.", nickname = "getDivisionsCount", notes = "get number of divisions in a circle.", response = CountResponse.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "discom", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Count for the requested entity.", response = CountResponse.class),
        @ApiResponse(code = 401, message = "Access token is missing or invalid.", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "The specified resource was not found.", response = ErrorResponse.class) })
    @RequestMapping(value = "/division/count",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CountResponse> getDivisionsCount(@NotNull @Min(0)@ApiParam(value = "Circle Id of the circle to count divisions for.", required = true, allowableValues = "") @Valid @RequestParam(value = "idCircle", required = true) Integer idCircle);


    @ApiOperation(value = "returns a division", nickname = "updateDivision", notes = "update details about a division", response = Division.class, authorizations = {
        @Authorization(value = "BearerAuth")    }, tags={ "discom", })
    @ApiResponses(value = { 
        @ApiResponse(code = 202, message = "Accepted", response = Division.class),
        @ApiResponse(code = 401, message = "Access token is missing or invalid.", response = ErrorResponse.class),
        @ApiResponse(code = 404, message = "The specified resource was not found.", response = ErrorResponse.class) })
    @RequestMapping(value = "/division",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Division> updateDivision(@ApiParam(value = ""  )  @Valid @RequestBody Division body);

}
