/*
 * Astute Energy API Specification.
 * Rest enpoints to be used with the Angular application for Astute Energy.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.astute.discom.dtos;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.Data;

@Data
public class Company implements Serializable {

	@JsonProperty("id")
	private Integer id;

	@JsonProperty("name")
	private String name;

	@JsonProperty("logo")
	private String logo;

	@JsonProperty("initials")
	private String initials;

	@JsonProperty("email")
	private String email;

	@JsonProperty("contact")
	private Long contact;

	@JsonProperty("address")
	private Address address;

	@JsonProperty("region")
	private List<Region> region;

	@JsonProperty("state")
	private State state;



}
