export class UserTypesModel {

    _id: string;
    name: string;
    // New Things
    // _id: string;    // autogenerated ID from database
    // name: string;   // type name
    entity: string; // 'admtc', 'academic', 'company', 'service-provider'
    permissions: {
        academicKit: {
            create: Boolean,
            read: Boolean,
            update: Boolean,
            delete: Boolean,
            test: {
                create: Boolean,
                read: Boolean,
                update: Boolean,
                delete: Boolean,
                documents: {
                    create: Boolean,
                    read: Boolean,
                    update: Boolean,
                    delete: Boolean
                }
            },
            documents: {
                create: Boolean,
                read: Boolean,
                update: Boolean,
                delete: Boolean
            }
        },
        users: {
            create: Boolean,
            read: Boolean,
            update: Boolean,
            delete: Boolean
        },
        rncpTitles: {
            create: Boolean,
            read: Boolean, // default true
            update: Boolean,
            delete: Boolean
        }
    }


    constructor() {
        this._id = '';
        this.name = '';
    }
}


const userTypes = [{
    '_id': 1,
    'name': 'director',
    'entity': 'admtc',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 2,
    'name': 'sales',
    'entity': 'admtc',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 3,
    'name': 'admtc-staff',
    'entity': 'admtc',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 4,
    'name': 'contract-signatory',
    'entity': 'admtc',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 5,
    'name': 'director',
    'entity': 'academic',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 6,
    'name': 'academic-staff',
    'entity': 'academic',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 7,
    'name': 'acad-linkto-admtc',
    'entity': 'academic',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 8,
    'name': 'corrector',
    'entity': 'academic',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 9,
    'name': 'cross-corrector',
    'entity': 'academic',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 10,
    'name': 'president-jury',
    'entity': 'academic',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 11,
    'name': 'member-jury',
    'entity': 'academic',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 12,
    'name': 'academic-committee-member',
    'entity': 'academic',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 13,
    'name': 'contract-signatory',
    'entity': 'academic',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 14,
    'name': 'legal-representative',
    'entity': 'academic',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 15,
    'name': 'mentor',
    'entity': 'company',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
},
{
    '_id': 16,
    'name': 'hr',
    'entity': 'company',
    'permissions': {
        'rncpTitles': {
            'create': true,
            'read': true, // default true
            'update': true,
            'delete': true
        }
    }
}];

