import { Injectable } from '@angular/core';

@Injectable()
export class countryService {
countryList = [];
  constructor() {
    this.countryList = [
                      { id: '1', EN: 'France' , FR: "France" },
                      { id: '2', EN: 'Afghanistan'  , FR: "Afghanistan"},
                      { id: '3', EN: 'South Africa' , FR: "Afrique du Sud" },
                      { id: '4', EN: 'Albanie'  , FR: "Albanie"},
                      { id: '5', EN: 'Algeria' , FR: "Algeria" },
                      { id: '6', EN: 'Germany'  , FR: "Allemagne"},
                      { id: '7', EN: 'Angola'  , FR: "Andorre"},
                      { id: '8', EN: 'Anguilla' , FR: "Angola" },
                      { id: '9', EN: 'Antarctique'  , FR: "Antartique"},
                      { id: '10', EN: 'Antigua and Barbuda'  , FR: "Antigua-et-Barbuda"},
                      { id: '11', EN: 'Netherlands Antilles'  , FR: "Antilles Néerlandaises"},
                      { id: '12', EN: 'Saudi Arabia'  , FR: "Arabie Saoudite"},
                      { id: '13', EN: 'Argentina'  , FR: "Argentine"},
                      { id: '14', EN: 'Armenia'  , FR: "Arménie"},
                      { id: '15', EN: 'Aruba'  , FR: "Aruba"},
                      { id: '16', EN: 'Australia'  , FR: "Australie"},
                      { id: '17', EN: 'Austria'  , FR: "Autriche"},
                      { id: '18', EN: 'Azerbaijan'  , FR: "Azerbaïdjan"},
                      { id: '19', EN: 'bahamas'  , FR: "Bahamas"},
                      { id: '20', EN: 'Bahrain' , FR: "Bahreïn" },
                      { id: '21', EN: 'Bangladesh'  , FR: "Bangladesh"},
                      { id: '22', EN: 'Barbados'  , FR: "Barbade"},
                      { id: '23', EN: 'Belarus' , FR: "Bélarus" },
                      { id: '24', EN: 'Belgium '  , FR: "Belgique"},
                      { id: '25', EN: 'Belize'  , FR: "Belize"},
                      { id: '26', EN: 'Benin'  , FR: "Bénin"},
                      { id: '27', EN: 'Bermuda'  , FR: "Bermudes"},
                      { id: '28', EN: 'Bhutan'  , FR: "Bhoutan"},
                      { id: '29', EN: 'Bolivia '  , FR: "Bolivie"},
                      { id: '30', EN: 'Bosnia and Herzegovina' , FR: "Bosnie-Herzégovine"},
                      { id: '31', EN: 'Botswana' , FR: "Botswana"},
                      { id: '32', EN: 'Brazil' , FR: "Brésil"},
                      { id: '33', EN: 'Brunei Darussalam ' , FR: "Brunéi Darussalam"},
                      { id: '34', EN: 'Bulgaria', FR: "Bulgarie" },
                      { id: '35', EN: 'Burkina Faso' , FR: "Burkina Faso"},
                      { id: '36', EN: 'Cambodia ' , FR: "Burundi"},
                      { id: '37', EN: 'Cape Verde  ' , FR: "Cambodge"},
                      { id: '38', EN: 'Chile' , FR: "Chile"},
                      { id: '39', EN: 'China ' , FR: "Chine"},
                      { id: '40', EN: 'Cyprus ' , FR: "Chypre"},
                      { id: '41', EN: 'Colombia' , FR: "Colombie"},
                      { id: '42', EN: 'Costa Rica', FR: "Costa Rica" },
                      { id: '43', EN: 'Ivory Coast' , FR: "Côte d&#39;Ivoire"},
                      { id: '44', EN: 'Croatia', FR: "Croatie" },
                      { id: '45', EN: 'Cuba' , FR: "Cuba"},
                      { id: '46', EN: 'Denmark ' , FR: "Danemark"},
                      { id: '47', EN: 'Djibouti ' , FR: "Djibouti"},
                      { id: '48', EN: 'Dominique' , FR: "Dominique"},
                      { id: '49', EN: 'Egypt', FR: "Égypte" },
                      { id: '50', EN: 'El Salvador', FR: "El Salvador" },
                      { id: '51', EN: 'United Arab Emirates', FR: "Émirats Arabes Unis" },
                      { id: '52', EN: 'Ecuador ', FR: "Équateur" },
                      { id: '53', EN: 'Eritrea ' , FR: "Érythrée"},
                      { id: '54', EN: 'Spain' , FR: "Espagne"},
                      { id: '55', EN: 'Estonia ' , FR: "Estonie"},
                      { id: '56', EN: 'Federated States of Micronesia', FR: "États Fédérés de Micronésie" },
                      { id: '57', EN: 'United States ' , FR: "États-Unis"},
                      { id: '58', EN: 'Ethiopia', FR: "Éthiopie" },
                      { id: '59', EN: 'Russian Federation ' , FR: "Fédération de Russie"},
                      { id: '60', EN: 'Fiji' , FR: "Fidji"},
                      { id: '61', EN: 'Finland ' , FR: "Finlande"},
                      { id: '62', EN: 'Gabon' , FR: "Gabon"},
                      { id: '63', EN: 'Gambia' , FR: "Gambie"},
                      { id: '64', EN: 'Georgia' , FR: "Géorgie"},
                      { id: '65', EN: 'Ghana' , FR: "Ghana"},
                      { id: '66', EN: 'Gibraltar' , FR: "Gibratlar"},
                      { id: '67', EN: 'Greece' , FR: "Grèce"},
                      { id: '68', EN: 'Granada', FR: "Grenade" },
                      { id: '69', EN: 'Greenland', FR: "Groenland" },
                      { id: '70', EN: 'Guadeloupe' , FR: "Guadeloupe"},
                      { id: '71', EN: 'Guam ', FR: "Guam" },
                      { id: '72', EN: 'Guatemala ' , FR: "Guatemala"},
                      { id: '73', EN: 'Guinea ', FR: "Guinée" },
                      { id: '74', EN: 'Guinea-Bissau' , FR: "Guinée-Bissau"},
                      { id: '75', EN: 'Equatorial Guinea', FR: "Guinée Équatoriale" },
                      { id: '76', EN: 'Guyana', FR: "Guyana" },
                      { id: '77', EN: 'French Guiana', FR: "Guyane Française" },
                      { id: '78', EN: 'Haiti' , FR: "Haïti"},
                      { id: '79', EN: 'Honduras' , FR: "Honduras"},
                      { id: '80', EN: 'Hong Kong' , FR: "Hong-Kong"},
                      { id: '82', EN: 'Hungary' , FR: "Hongrie"},
                      { id: '83', EN: 'Bouvet Island ' , FR: "Île Bouvet"},
                      { id: '84', EN: 'Christmas Island' , FR: "Île Christmas"},
                      { id: '85', EN: 'Isle of Man' , FR: "Île de Man"},
                      { id: '86', EN: 'Norfolk Island' , FR: "Île Norfolk"},
                      { id: '87', EN: 'Islands (malvinas) Falkland', FR: "Îles (malvinas) Falkland" },
                      { id: '88', EN: '�land Islands', FR: "Îles Åland" },
                      { id: '89', EN: 'Cocos (Keeling) Islands ' , FR: "Îles Cocos (Keeling)"},
                      { id: '90', EN: 'Cook Islands', FR: "Îles Cook" },
                      { id: '91', EN: 'Faroe Islands' , FR: "Îles Féroé"},
                      { id: '92', EN: 'Solomon Islands' , FR: "Îles Salomon"},
                      { id: '93', EN: 'Turks and Caicos Islands', FR: "Îles Turks et Caïques" },
                      { id: '94', EN: 'British Virgin Islands', FR: "Îles Vierges Britanniques" },
                      { id: '95', EN: 'United States Virgin Islands' , FR: "Îles Vierges des États-Unis"},
                      { id: '96', EN: 'India', FR: "Inde" },
                      { id: '97', EN: 'Indonesia ', FR: "Indonésie" },
                      { id: '98', EN: 'Iraq ', FR: "Iraq" },
                      { id: '99', EN: 'Ireland' , FR: "Irlande"},
                      { id: '100', EN: 'Iceland' , FR: "Islande"},
                      { id: '101', EN: 'Israel' , FR: "Israël"},
                      { id: '102', EN: 'Italy' , FR: "Italie"},
                      { id: '103', EN: 'Libyan Arab Jamahiriya', FR: "Jamahiriya Arabe Libyenne" },
                      { id: '104', EN: 'Jamaica', FR: "Jamaïque" },
                      { id: '105', EN: 'Japan', FR: "Japon" },
                      { id: '106', EN: 'Jordan', FR: "Jordanie" },
                      { id: '107', EN: 'Kazakhstan', FR: "Kazakhstan" },
                      { id: '108', EN: 'Kenya' , FR: "Kenya"},
                      { id: '109', EN: 'Kyrgyzstan' , FR: "Kirghizistan"},
                      { id: '110', EN: 'Kiribati' , FR: "Kiribati"},
                      { id: '111', EN: 'Kuwait ' , FR: "Koweït"},
                      { id: '112', EN: 'Lesotho' , FR: "Lesotho"},
                      { id: '113', EN: 'Latvia', FR: "Lettonie" },
                      { id: '114', EN: 'Lebanon' , FR: "Liban"},
                      { id: '115', EN: 'Liberia' , FR: "Libéria"},
                      { id: '116', EN: 'Liechtenstein' , FR: "Liechtenstein"},
                      { id: '117', EN: 'Lithuania' , FR: "Lituanie"},
                      { id: '118', EN: 'Luxembourg' , FR: "Luxembourg"},
                      { id: '119', EN: 'Macau', FR: "Macao" },
                      { id: '120', EN: 'Macau', FR: "Madagascar" },
                      { id: '121', EN: 'Malaysia' , FR: "Malaisie"},
                      { id: '122', EN: 'Malawi' , FR: "Malawi"},
                      { id: '123', EN: 'Maldives' , FR: "Maldives"},
                      { id: '124', EN: 'Mali' , FR: "Mali"},
                      { id: '125', EN: 'Malta' , FR: "Malte"},
                      { id: '126', EN: 'Morocco' , FR: "Maroc"},
                      { id: '127', EN: 'Martinique' , FR: "Martinique"},
                      { id: '128', EN: 'Mauritius' , FR: "Maurice"},
                      { id: '129', EN: 'Mauritania', FR: "Mauritanie" },
                      { id: '130', EN: 'Mayotte' , FR: "Mayotte"},
                      { id: '131', EN: 'Mexico' , FR: "Mexique"},
                      { id: '132', EN: 'Monaco' , FR: "Monaco"},
                      { id: '133', EN: 'Mongolia' , FR: "Mongolie"},
                      { id: '134', EN: 'Montserrat' , FR: "Montserrat"},
                      { id: '135', EN: 'Mozambique' , FR: "Mozambique"},
                      { id: '136', EN: 'Myanmar' , FR: "Myanmar"},
                      { id: '137', EN: 'Namibia' , FR: "Namibie"},
                      { id: '138', EN: 'Nauru' , FR: "Nauru"},
                      { id: '139', EN: 'Nepal' , FR: "Népal"},
                      { id: '140', EN: 'Nicaragua', FR: "Nicaragua" },
                      { id: '141', EN: 'Niger' , FR: "Niger"},
                      { id: '142', EN: 'Nigeria', FR: "Nigéria" },
                      { id: '143', EN: 'Niue', FR: "Niué" },
                      { id: '144', EN: 'Norway' , FR: "Norvège"},
                      { id: '145', EN: 'New Caledonia' , FR: "Nouvelle-Calédonie"},
                      { id: '146', EN: 'New Zealand', FR: "Nouvelle-Zélande" },
                      { id: '147', EN: 'Oman', FR: "Oman" },
                      { id: '148', EN: 'Uganda', FR: "Ouganda" },
                      { id: '149', EN: 'Uzbekistan' , FR: "Ouzbékistan"},
                      { id: '150', EN: 'Pakistan ' , FR: "Pakistan"},
                      { id: '151', EN: 'Palau', FR: "Palaos" },
                      { id: '152', EN: 'Panama' , FR: "Panama"},
                      { id: '153', EN: 'Papua New Guinea', FR: "Papouasie-Nouvelle-Guinée" },
                      { id: '154', EN: 'Netherlands' , FR: "Pays-Bas"},
                      { id: '155', EN: 'Peru', FR: "Pérou" },
                      { id: '156', EN: 'Philippines', FR: "Philippines" },
                      { id: '157', EN: 'Pitcairn ' , FR: "Pitcairn"},
                      { id: '158', EN: 'Poland'  , FR: "Pologne"},
                      { id: '159', EN: 'French Polynesia', FR: "Polynésie française"},
                      { id: '160', EN: 'Puerto Rico' , FR: " Porto Rico"},
                      { id: '161', EN: 'Portugal', FR: "Portugal"},
                      { id: '162', EN: 'Qatar'  , FR: "Qatar"},
                      { id: '163', EN: 'Syrian Arab Republic' , FR: "République arabe syrienne" },
                      { id: '164', EN: 'Central African Republic', FR: "République centrafricaine"},
                      { id: '165', EN: 'Republic of Korea', FR: "République de Corée"},
                      { id: '166', EN: 'Republic of Moldova'  , FR: " République de Moldavie"},
                      { id: '167', EN: 'Democratic Republic of Congo'  , FR: "République Démocratique du Congo"},
                      { id: '168', EN: 'Lao Peoples Democratic Republic'  , FR: "République démocratique populaire lao"},
                      { id: '169', EN: 'Dominican Republic'  , FR: "République Dominicaine"},
                      { id: '170', EN: 'Islamic Republic of Iran'  , FR: "République islamique d'Iran"},
                      { id: '171', EN: 'Democratic Peoples Republic of Korea' , FR: "République Populaire Démocratique de Corée" },
                      { id: '172', EN: 'Czech Republic'  , FR: "République Tchèque"},
                      { id: '173', EN: 'United Republic of Tanzania' , FR: "République-Unie de Tanzanie" },
                      { id: '174', EN: 'Meeting'  , FR: "Réunion"},
                      { id: '175', EN: 'United Kingdom'  , FR: "Royaume-Uni"},
                      { id: '176', EN: 'Rwanda'  , FR: "Rwanda"},
                      { id: '177', EN: 'Western Sahara'  , FR: "Sahara occidental"},
                      { id: '178', EN: 'Saint Kitts and Nevis'  , FR: "Saint-Christophe-et-Niévès"},
                      { id: '179', EN: 'San Marino'  , FR: "Saint-Marin"},
                      { id: '180', EN: 'Holy See (state of Vatican City)' , FR: "Saint-Siège (État de la Cité du Vatican)" },
                      { id: '181', EN: 'Saint Vincent and the Grenadines'  , FR: "Saint-Vincent-et-les-Grenadines"},
                      { id: '182', EN: 'Sainte-H�l�ne'  , FR: "Sainte-H l ne"},
                      { id: '183', EN: 'Saint Lucia'  , FR: "Saint Lucia"},
                      { id: '184', EN: 'Samoa'  , FR: "Samoa"},
                      { id: '185', EN: 'American Samoa'  , FR: "Samoa américaines"},
                      { id: '186', EN: 'Sao Tome and Principe'  , FR: "Sao Tomé et Principe"},
                      { id: '187', EN: 'Senegal'  , FR: "Sénégal"},
                      { id: '188', EN: 'Serbia and Montenegro' , FR: "Serbie et Monténégro" },
                      { id: '189', EN: 'Seychelles'  , FR: "les Seychelles "},
                      { id: '190', EN: 'Sierra Leone'  , FR: "Sierra Leone"},
                      { id: '191', EN: 'Singapore'  , FR: "Singapour"},
                      { id: '192', EN: 'Slovakia'  , FR: "Slovaquie"},
                      { id: '193', EN: 'Slovenia'  , FR: "Slovénie"},
                      { id: '194', EN: 'Somalia'  , FR: "Somalie"},
                      { id: '195', EN: 'Sudan'  , FR: "Soudan"},
                      { id: '196', EN: 'Sri Lanka'  , FR: "Sri Lanka"},
                      { id: '197', EN: 'Sweden'  , FR: "Suède"},
                      { id: '198', EN: 'Suriname'  , FR: "Suriname"},
                      { id: '199', EN: 'Swaziland'  , FR: "Swaziland"},
                      { id: '200', EN: 'Tajikistan'  , FR: "Tadjikistan"},
                      { id: '201', EN: 'Taiwan'  , FR: "Taïwan"},
                      { id: '202', EN: 'Chad'  , FR: "Chad"},
                      { id: '203', EN: 'Palestinian Territory Occupied', FR: "Territoire palestinien occupé"},
                      { id: '204', EN: 'Thailand'  , FR: "Thaïlande"},
                      { id: '205', EN: 'Timor-Leste'  , FR: "Timor-Leste"},
                      { id: '206', EN: 'Togo'  , FR: "Aller"},
                      { id: '207', EN: 'Tokelau'  , FR: "Tokelau"},
                      { id: '208', EN: 'Tonga'  , FR: "Tonga"},
                      { id: '209', EN: 'Trinidad and Tobago' , FR: "Trinité-et-Tobago" },
                      { id: '210', EN: 'Tunisia'  , FR: "Tunisie"},
                      { id: '211', EN: 'Turkmenistan'  , FR: "Turkménistan"},
                      { id: '212', EN: 'Turkey'  , FR: "dinde"},
                      { id: '213', EN: 'Tuvalu'  , FR: "Tuvalu"},
                      { id: '214', EN: 'Ukraine'  , FR: "Ukraine"},
                      { id: '215', EN: 'Uruguay'  , FR: "Uruguay"},
                      { id: '216', EN: 'Vanuatu'  , FR: "Vanuatu"},
                      { id: '217', EN: 'Venezuela'  , FR: "Venezuela"},
                      { id: '218', EN: 'Viet Nam'  , FR: "Viet Nam"},
                      { id: '219', EN: 'Wallis and Futuna' , FR: "Wallis et Futuna" },
                      { id: '220', EN: 'Yemen'  , FR: "Yémen"},
                      { id: '221', EN: 'Zambia '  , FR: "Zambie"},
                      { id: '222', EN: 'Zimbabwe' , FR: "Zimbabwe" }
                  ];
  }

  getCountryList(lang){

  }

}
